# 异步操作

## Callback ES5

```js
function loadScript (src, callback) {
    let script = document.createElement('script')
    script.src = src
    script.onload = () => {
        callback(src)
    }
    document.head.append(script)
}

loadScript('./1.js', function (script) {            // 回调地狱
    if (script.message) {
        // 监控上报逻辑
    } else {
        loadScript('./2,js, function (script) {
            console.log(script);
            loadScript('./3,js, function (script) {
                console.log(script);
            })
        })
    }
})
```

## Promise ES6

```js
function loadScript (src) {
    // pending, undefined
    return new Promise((resolve, reject) => {
        let script = document.createElement('script')
        script.src = src
        script.onload = () => resolve(src)      // fulfilled, result
        script.onerror = (err) => reject(err)   // rejected, error
        document.head.append(script)
    })
}

loadScript('./1.js')
    .then(loadScript('./2.js'))
    .then(loadScript('./3.js'))
```

### Then

- promise.then(onFulfilled, onRejected)
  - onFulfilled, onRejected是函数
  - 但是loadScript('./2.js')是返回值，返回的是Promise对象，所以这里为什么能成功运行？
  - loadScript('./2.js')是表达式，是表达式就需要被执行，执行就执行了相应的代码
- .then为什么能链式调用？
  - .then 返回Promise对象，因为.then(loadScript('./2.js'))没有正常执行
  - .then 返回新的空的Promise对象，然后就可以接着继续正常执行
- 关于运行顺序
  - 如果使用```.then(()=>{},(err)=>{})```不会影响后续.then的运行，就是跳到(err)=>{}后，执行相应语句后，后续的.then还是会运行的，因为返回了空的Promise对象
  - 如果使用```.catch(err=>{})```，catch前的.then如果有reject，则剩下的.then不运行，catch后的不受影响，catch其实是```then(undefined, () => {})```的语法糖，而Promise对象其实自带try catch，一有错误就会跳到catch

```js
loadScript('./1.js')
    .then(() => {
        return loadScript('./2.js')         // 不加return的话，相当于没有返回值，就会生成一个空的Promise对象，导致后续代码不会进入reject，而是正常执行
    }, (err) => {
        console.log(err)
    })
    .then(() => {
        loadScript('./3.js')
    }, (err) => {
        console.log(err)
    })
// promise.then(onFulfilled, onRejected)
// onFulfilled, onRejected是函数
// 但是loadScript('./2.js')是返回值，返回的是Promise对象
// 所以这里为什么能成功运行？
// loadScript('./2.js')是表达式，是表达式就需要被执行，执行就执行了相应的代码

// .then为什么能链式调用？
// .then 返回Promise对象
// 因为.then(loadScript('./2.js'))没有正常执行
// .then 返回新的空的Promise对象，然后就可以接着继续正常执行

// onFulfilled 和 onRejected 对应 resolve() 和 reject()
```

## Resolve & Reject

- Promise静态方法
  - Promise.resolve()
  - Promise.reject()

```js
function test(bool) {                   // 有异步操作和没异步操作都有可能
    if (bool) {
        return new Promise((resolve, reject) => {
            resolve(2)
        })
    } else {
        // return 1
        // return Promise.resolve(1)
        return Promise.reject(new Error('test'))
    }
}

test(0).then((value) => {
    console.log(value)
}, (err) => {
    console.log(err)
})
```

## Catch

```js
function loadScript (src) {
    // pending, undefined
    return new Promise((resolve, reject) => {
        let script = document.createElement('script')
        script.src = src
        script.onload = () => resolve(src)      // fulfilled, result
        script.onerror = (err) => reject(err)   // rejected, error
        document.head.append(script)
    })
}

loadScript('./1.js')
    .then(() => {
        return loadScript('./2.js')
    })
    .then(() => {
        return loadScript('./3.js')
    })
    .catch(err => {
        console.log(err)
    })
    // catch 只能捕获reject 不要用throw new Error
```

## All

```js
const p1 = Promise.resolve(1)
const p2 = Promise.resolve(2)
const p3 = Promise.resolve(3)

Promise.all([p1, p2, p3])
    .then((value) => {
        console.log(value)
    })
```

## Race

- 例如：多线路加载图片

```js
const p1 = () => {
    return new Promise((resolve, reject) => {
        setTimeout(function () {
            resolve(1)
        }, 1000)
    })
}
const p2 = () => {
    return new Promise((resolve, reject) => {
        setTimeout(function () {
            resolve(2)
        }, 0)
    })
}
Promise.race([p1(), p2()])
    .then((value) => {
        console.log(value)              // 2
    })
```
